name: CI

on:
  issues:
    types: [opened]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: vbasem/first-interaction@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "I do this for my own and no one else is responsible for my crap."
        pr-message: "My PRs are my own crap as well, so I am adding this to reemphisize it!"
