name: CI

on:
  issues:
    types: [opened]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: bvasegh/first-interaction@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '# Message with markdown.\nThis is the message that will be displayed on users first issue.'
        pr-message: 'Message that will be displayed on users first pr. Look, a `code block` for markdown.'
